#===============================================================================
# Skinkit patch — installs the runtime skin loader into the asar.
#
# Sourced by: app-asar.sh
# Sourced globals:
#   source_dir      — repo root
#   app_staging_dir — directory containing app.asar.contents/
#===============================================================================

patch_skinkit() {
	echo 'Installing skinkit (runtime skin loader)...'

	local skinkit_src="$source_dir/scripts/skinkit"
	local skinkit_dst="$app_staging_dir/app.asar.contents/skinkit"

	if [ ! -d "$skinkit_src" ]; then
		echo 'Warning: scripts/skinkit not found, skipping skinkit install'
		return 0
	fi

	mkdir -p "$skinkit_dst" || exit 1
	cp -a "$skinkit_src/." "$skinkit_dst/" || exit 1

	# Wire skinkit into the frame-fix-entry.js generated by app-asar.sh.
	# The entry currently looks like:
	#   require('./frame-fix-wrapper.js');
	#   require('./<original main>');
	# We splice a skinkit require between them.
	local entry="$app_staging_dir/app.asar.contents/frame-fix-entry.js"
	if [ ! -f "$entry" ]; then
		echo 'Error: frame-fix-entry.js not found; run after frame-fix step'
		exit 1
	fi

	if grep -q "skinkit/_skinkit" "$entry"; then
		echo 'Skinkit already wired into frame-fix-entry.js'
		return 0
	fi

	# Insert a require call right after the frame-fix-wrapper require.
	awk '
		{ print }
		/require..\.\/frame-fix-wrapper\.js/ {
			print "// Skinkit: load skin system";
			print "try { require(\"./skinkit/_skinkit\")(require(\"electron\")); } catch (e) { console.error(\"[Skinkit] init failed:\", e); }";
		}
	' "$entry" > "$entry.new" && mv "$entry.new" "$entry" || exit 1

	echo 'Skinkit installed and wired into frame-fix-entry.js'
}
